"""Text layer of an imported payment PDF.

Payment documents (quittances, supplier bills) are generated by accounting
software, so their text layer is exact — no OCR or AI is involved. A PDF with no
text layer is a scan, which this workflow cannot read; that is reported to the
user instead of producing an empty, silently-unmatched payment.
"""

import pypdfium2

from facturo.i18n import tr


class PaymentParseError(Exception):
    """User-facing failure; the message (already translated) is shown as-is in the UI."""


def extract_text(raw: bytes) -> str:
    """All pages' text, joined with "\\n".

    Raises PaymentParseError when the bytes are not a readable PDF or when no
    page carries any text (e.g. a scanned image PDF).
    """
    try:
        pdf = pypdfium2.PdfDocument(raw)
    except pypdfium2.PdfiumError as e:
        if "password" in str(e).lower():
            raise PaymentParseError(tr("err.payment_pdf_protected")) from e
        raise PaymentParseError(tr("err.payment_pdf_unreadable")) from e
    try:
        pages = []
        for i in range(len(pdf)):
            page = pdf.get_page(i)
            try:
                textpage = page.get_textpage()
                try:
                    pages.append(textpage.get_text_range())
                finally:
                    textpage.close()
            finally:
                page.close()
    finally:
        pdf.close()

    text = "\n".join(pages)
    if not text.strip():
        raise PaymentParseError(tr("err.payment_pdf_no_text"))
    return text
