"""Text layer of an imported payment PDF.

Payment documents (quittances, supplier bills) are generated by accounting
software, so their text layer is exact — no OCR or AI is involved. A PDF with no
text layer is a scan, which this workflow cannot read; that is reported to the
user in French instead of producing an empty, silently-unmatched payment.
"""

import pypdfium2


class PaymentParseError(Exception):
    """User-facing failure; the French message is shown as-is in the UI."""


def extract_text(raw: bytes) -> str:
    """All pages' text, joined with "\\n".

    Raises PaymentParseError when the bytes are not a readable PDF or when no
    page carries any text (e.g. a scanned image PDF).
    """
    try:
        pdf = pypdfium2.PdfDocument(raw)
    except pypdfium2.PdfiumError as e:
        if "password" in str(e).lower():
            raise PaymentParseError(
                "Ce PDF est protégé par un mot de passe. "
                "Retirez la protection puis importez-le à nouveau."
            ) from e
        raise PaymentParseError("Ce fichier n'est pas un PDF lisible.") from e
    try:
        pages = []
        for i in range(len(pdf)):
            page = pdf.get_page(i)
            try:
                textpage = page.get_textpage()
                try:
                    pages.append(textpage.get_text_range())
                finally:
                    textpage.close()
            finally:
                page.close()
    finally:
        pdf.close()

    text = "\n".join(pages)
    if not text.strip():
        raise PaymentParseError(
            "Ce PDF ne contient pas de texte lisible (document numérisé ?). "
            "Importez le PDF original produit par le logiciel de l'émetteur."
        )
    return text
